// This file contains definitions of all configuration protos.
// These messages should only be stored in textual or in-memory form (i.e. not
// the binary format), so feed free to change any field numbers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: heyp/proto/app.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Distribution int32

const (
	Distribution_DIST_UNSET       Distribution = 0
	Distribution_DIST_CONSTANT    Distribution = 1
	Distribution_DIST_UNIFORM     Distribution = 2
	Distribution_DIST_EXPONENTIAL Distribution = 3
)

// Enum value maps for Distribution.
var (
	Distribution_name = map[int32]string{
		0: "DIST_UNSET",
		1: "DIST_CONSTANT",
		2: "DIST_UNIFORM",
		3: "DIST_EXPONENTIAL",
	}
	Distribution_value = map[string]int32{
		"DIST_UNSET":       0,
		"DIST_CONSTANT":    1,
		"DIST_UNIFORM":     2,
		"DIST_EXPONENTIAL": 3,
	}
)

func (x Distribution) Enum() *Distribution {
	p := new(Distribution)
	*p = x
	return p
}

func (x Distribution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Distribution) Descriptor() protoreflect.EnumDescriptor {
	return file_heyp_proto_app_proto_enumTypes[0].Descriptor()
}

func (Distribution) Type() protoreflect.EnumType {
	return &file_heyp_proto_app_proto_enumTypes[0]
}

func (x Distribution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Distribution) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Distribution(num)
	return nil
}

// Deprecated: Use Distribution.Descriptor instead.
func (Distribution) EnumDescriptor() ([]byte, []int) {
	return file_heyp_proto_app_proto_rawDescGZIP(), []int{0}
}

type TestLopriClientConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumConns       *int32                                 `protobuf:"varint,1,opt,name=num_conns,json=numConns,def=20" json:"num_conns,omitempty"`
	WorkloadStages []*TestLopriClientConfig_WorkloadStage `protobuf:"bytes,2,rep,name=workload_stages,json=workloadStages" json:"workload_stages,omitempty"`
}

// Default values for TestLopriClientConfig fields.
const (
	Default_TestLopriClientConfig_NumConns = int32(20)
)

func (x *TestLopriClientConfig) Reset() {
	*x = TestLopriClientConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heyp_proto_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestLopriClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLopriClientConfig) ProtoMessage() {}

func (x *TestLopriClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_heyp_proto_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLopriClientConfig.ProtoReflect.Descriptor instead.
func (*TestLopriClientConfig) Descriptor() ([]byte, []int) {
	return file_heyp_proto_app_proto_rawDescGZIP(), []int{0}
}

func (x *TestLopriClientConfig) GetNumConns() int32 {
	if x != nil && x.NumConns != nil {
		return *x.NumConns
	}
	return Default_TestLopriClientConfig_NumConns
}

func (x *TestLopriClientConfig) GetWorkloadStages() []*TestLopriClientConfig_WorkloadStage {
	if x != nil {
		return x.WorkloadStages
	}
	return nil
}

type TestLopriClientConfig_WorkloadStage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcSizeBytes     *int32        `protobuf:"varint,1,opt,name=rpc_size_bytes,json=rpcSizeBytes,def=4096" json:"rpc_size_bytes,omitempty"`
	TargetAverageBps *float64      `protobuf:"fixed64,2,opt,name=target_average_bps,json=targetAverageBps,def=1e+07" json:"target_average_bps,omitempty"`
	InterarrivalDist *Distribution `protobuf:"varint,3,opt,name=interarrival_dist,json=interarrivalDist,enum=heyp.proto.Distribution,def=3" json:"interarrival_dist,omitempty"`
	RunDur           *string       `protobuf:"bytes,4,opt,name=run_dur,json=runDur,def=30s" json:"run_dur,omitempty"`
}

// Default values for TestLopriClientConfig_WorkloadStage fields.
const (
	Default_TestLopriClientConfig_WorkloadStage_RpcSizeBytes     = int32(4096)
	Default_TestLopriClientConfig_WorkloadStage_TargetAverageBps = float64(1e+07)
	Default_TestLopriClientConfig_WorkloadStage_InterarrivalDist = Distribution_DIST_EXPONENTIAL
	Default_TestLopriClientConfig_WorkloadStage_RunDur           = string("30s")
)

func (x *TestLopriClientConfig_WorkloadStage) Reset() {
	*x = TestLopriClientConfig_WorkloadStage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heyp_proto_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestLopriClientConfig_WorkloadStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestLopriClientConfig_WorkloadStage) ProtoMessage() {}

func (x *TestLopriClientConfig_WorkloadStage) ProtoReflect() protoreflect.Message {
	mi := &file_heyp_proto_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestLopriClientConfig_WorkloadStage.ProtoReflect.Descriptor instead.
func (*TestLopriClientConfig_WorkloadStage) Descriptor() ([]byte, []int) {
	return file_heyp_proto_app_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestLopriClientConfig_WorkloadStage) GetRpcSizeBytes() int32 {
	if x != nil && x.RpcSizeBytes != nil {
		return *x.RpcSizeBytes
	}
	return Default_TestLopriClientConfig_WorkloadStage_RpcSizeBytes
}

func (x *TestLopriClientConfig_WorkloadStage) GetTargetAverageBps() float64 {
	if x != nil && x.TargetAverageBps != nil {
		return *x.TargetAverageBps
	}
	return Default_TestLopriClientConfig_WorkloadStage_TargetAverageBps
}

func (x *TestLopriClientConfig_WorkloadStage) GetInterarrivalDist() Distribution {
	if x != nil && x.InterarrivalDist != nil {
		return *x.InterarrivalDist
	}
	return Default_TestLopriClientConfig_WorkloadStage_InterarrivalDist
}

func (x *TestLopriClientConfig_WorkloadStage) GetRunDur() string {
	if x != nil && x.RunDur != nil {
		return *x.RunDur
	}
	return Default_TestLopriClientConfig_WorkloadStage_RunDur
}

var File_heyp_proto_app_proto protoreflect.FileDescriptor

var file_heyp_proto_app_proto_rawDesc = []byte{
	0x0a, 0x14, 0x68, 0x65, 0x79, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x79, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xff, 0x02, 0x0a, 0x15, 0x54, 0x65, 0x73, 0x74, 0x4c, 0x6f, 0x70, 0x72, 0x69,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x09,
	0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x3a,
	0x02, 0x32, 0x30, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x73, 0x12, 0x58, 0x0a,
	0x0f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x68, 0x65, 0x79, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x4c, 0x6f, 0x70, 0x72, 0x69, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x1a, 0xea, 0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x72, 0x70, 0x63,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x3a, 0x04, 0x34, 0x30, 0x39, 0x36, 0x52, 0x0c, 0x72, 0x70, 0x63, 0x53, 0x69, 0x7a, 0x65,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x12, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f,
	0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x3a, 0x08, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x52, 0x10, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x42, 0x70, 0x73, 0x12, 0x57, 0x0a,
	0x11, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x64, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x68, 0x65, 0x79, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x3a, 0x10, 0x44, 0x49, 0x53, 0x54, 0x5f, 0x45, 0x58, 0x50, 0x4f, 0x4e, 0x45, 0x4e,
	0x54, 0x49, 0x41, 0x4c, 0x52, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x44, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x5f, 0x64, 0x75,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x03, 0x33, 0x30, 0x73, 0x52, 0x06, 0x72, 0x75,
	0x6e, 0x44, 0x75, 0x72, 0x2a, 0x59, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x49, 0x53, 0x54, 0x5f, 0x55, 0x4e, 0x53,
	0x45, 0x54, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x49, 0x53, 0x54, 0x5f, 0x43, 0x4f, 0x4e,
	0x53, 0x54, 0x41, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x49, 0x53, 0x54, 0x5f,
	0x55, 0x4e, 0x49, 0x46, 0x4f, 0x52, 0x4d, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x49, 0x53,
	0x54, 0x5f, 0x45, 0x58, 0x50, 0x4f, 0x4e, 0x45, 0x4e, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x03, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6c,
	0x75, 0x79, 0x6f, 0x6c, 0x2f, 0x68, 0x65, 0x79, 0x70, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_heyp_proto_app_proto_rawDescOnce sync.Once
	file_heyp_proto_app_proto_rawDescData = file_heyp_proto_app_proto_rawDesc
)

func file_heyp_proto_app_proto_rawDescGZIP() []byte {
	file_heyp_proto_app_proto_rawDescOnce.Do(func() {
		file_heyp_proto_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_heyp_proto_app_proto_rawDescData)
	})
	return file_heyp_proto_app_proto_rawDescData
}

var file_heyp_proto_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_heyp_proto_app_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heyp_proto_app_proto_goTypes = []interface{}{
	(Distribution)(0),                           // 0: heyp.proto.Distribution
	(*TestLopriClientConfig)(nil),               // 1: heyp.proto.TestLopriClientConfig
	(*TestLopriClientConfig_WorkloadStage)(nil), // 2: heyp.proto.TestLopriClientConfig.WorkloadStage
}
var file_heyp_proto_app_proto_depIdxs = []int32{
	2, // 0: heyp.proto.TestLopriClientConfig.workload_stages:type_name -> heyp.proto.TestLopriClientConfig.WorkloadStage
	0, // 1: heyp.proto.TestLopriClientConfig.WorkloadStage.interarrival_dist:type_name -> heyp.proto.Distribution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_heyp_proto_app_proto_init() }
func file_heyp_proto_app_proto_init() {
	if File_heyp_proto_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heyp_proto_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestLopriClientConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_heyp_proto_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestLopriClientConfig_WorkloadStage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heyp_proto_app_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heyp_proto_app_proto_goTypes,
		DependencyIndexes: file_heyp_proto_app_proto_depIdxs,
		EnumInfos:         file_heyp_proto_app_proto_enumTypes,
		MessageInfos:      file_heyp_proto_app_proto_msgTypes,
	}.Build()
	File_heyp_proto_app_proto = out.File
	file_heyp_proto_app_proto_rawDesc = nil
	file_heyp_proto_app_proto_goTypes = nil
	file_heyp_proto_app_proto_depIdxs = nil
}
