#!/bin/bash

outdir="$1"
port="$2"

if [[ $# -ne 2 ]]; then
    echo usage: collect-envoy-stats outdir port >&2
    exit 2
fi

mkdir -p "$outdir"
while true; do
    now=$(date --iso-8601=seconds)
    curl -s -o "$outdir/$now-stats" "http://localhost:$port/stats"
    curl -s -o "$outdir/$now-clusters" "http://localhost:$port/clusters"
    sleep 3
done
