// This file contains definitions of all configuration protos.
// These messages should only be stored in textual or in-memory form (i.e. not
// the binary format), so feed free to change any field numbers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: heyp/proto/fakehost.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FakeFG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcDc            *string `protobuf:"bytes,1,opt,name=src_dc,json=srcDc" json:"src_dc,omitempty"`
	DstDc            *string `protobuf:"bytes,2,opt,name=dst_dc,json=dstDc" json:"dst_dc,omitempty"`
	Job              *string `protobuf:"bytes,3,opt,name=job" json:"job,omitempty"`
	MinHostUsage     *int64  `protobuf:"varint,4,opt,name=min_host_usage,json=minHostUsage" json:"min_host_usage,omitempty"`
	MaxHostUsage     *int64  `protobuf:"varint,5,opt,name=max_host_usage,json=maxHostUsage" json:"max_host_usage,omitempty"`
	ApprovalBps      *int64  `protobuf:"varint,6,opt,name=approval_bps,json=approvalBps" json:"approval_bps,omitempty"`
	TargetNumSamples *int32  `protobuf:"varint,7,opt,name=target_num_samples,json=targetNumSamples,def=200" json:"target_num_samples,omitempty"`
}

// Default values for FakeFG fields.
const (
	Default_FakeFG_TargetNumSamples = int32(200)
)

func (x *FakeFG) Reset() {
	*x = FakeFG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heyp_proto_fakehost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FakeFG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeFG) ProtoMessage() {}

func (x *FakeFG) ProtoReflect() protoreflect.Message {
	mi := &file_heyp_proto_fakehost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeFG.ProtoReflect.Descriptor instead.
func (*FakeFG) Descriptor() ([]byte, []int) {
	return file_heyp_proto_fakehost_proto_rawDescGZIP(), []int{0}
}

func (x *FakeFG) GetSrcDc() string {
	if x != nil && x.SrcDc != nil {
		return *x.SrcDc
	}
	return ""
}

func (x *FakeFG) GetDstDc() string {
	if x != nil && x.DstDc != nil {
		return *x.DstDc
	}
	return ""
}

func (x *FakeFG) GetJob() string {
	if x != nil && x.Job != nil {
		return *x.Job
	}
	return ""
}

func (x *FakeFG) GetMinHostUsage() int64 {
	if x != nil && x.MinHostUsage != nil {
		return *x.MinHostUsage
	}
	return 0
}

func (x *FakeFG) GetMaxHostUsage() int64 {
	if x != nil && x.MaxHostUsage != nil {
		return *x.MaxHostUsage
	}
	return 0
}

func (x *FakeFG) GetApprovalBps() int64 {
	if x != nil && x.ApprovalBps != nil {
		return *x.ApprovalBps
	}
	return 0
}

func (x *FakeFG) GetTargetNumSamples() int32 {
	if x != nil && x.TargetNumSamples != nil {
		return *x.TargetNumSamples
	}
	return Default_FakeFG_TargetNumSamples
}

type FakeHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId *uint64 `protobuf:"varint,1,opt,name=host_id,json=hostId" json:"host_id,omitempty"`
	FgIds  []int32 `protobuf:"varint,2,rep,name=fg_ids,json=fgIds" json:"fg_ids,omitempty"` // [-1] indicates use all fgs
}

func (x *FakeHost) Reset() {
	*x = FakeHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heyp_proto_fakehost_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FakeHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeHost) ProtoMessage() {}

func (x *FakeHost) ProtoReflect() protoreflect.Message {
	mi := &file_heyp_proto_fakehost_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeHost.ProtoReflect.Descriptor instead.
func (*FakeHost) Descriptor() ([]byte, []int) {
	return file_heyp_proto_fakehost_proto_rawDescGZIP(), []int{1}
}

func (x *FakeHost) GetHostId() uint64 {
	if x != nil && x.HostId != nil {
		return *x.HostId
	}
	return 0
}

func (x *FakeHost) GetFgIds() []int32 {
	if x != nil {
		return x.FgIds
	}
	return nil
}

type HostSimulatorConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fgs       []*FakeFG   `protobuf:"bytes,1,rep,name=fgs" json:"fgs,omitempty"`
	Hosts     []*FakeHost `protobuf:"bytes,2,rep,name=hosts" json:"hosts,omitempty"`
	ReportDur *string     `protobuf:"bytes,3,opt,name=report_dur,json=reportDur,def=3s" json:"report_dur,omitempty"`
}

// Default values for HostSimulatorConfig fields.
const (
	Default_HostSimulatorConfig_ReportDur = string("3s")
)

func (x *HostSimulatorConfig) Reset() {
	*x = HostSimulatorConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heyp_proto_fakehost_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostSimulatorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSimulatorConfig) ProtoMessage() {}

func (x *HostSimulatorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_heyp_proto_fakehost_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSimulatorConfig.ProtoReflect.Descriptor instead.
func (*HostSimulatorConfig) Descriptor() ([]byte, []int) {
	return file_heyp_proto_fakehost_proto_rawDescGZIP(), []int{2}
}

func (x *HostSimulatorConfig) GetFgs() []*FakeFG {
	if x != nil {
		return x.Fgs
	}
	return nil
}

func (x *HostSimulatorConfig) GetHosts() []*FakeHost {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *HostSimulatorConfig) GetReportDur() string {
	if x != nil && x.ReportDur != nil {
		return *x.ReportDur
	}
	return Default_HostSimulatorConfig_ReportDur
}

var File_heyp_proto_fakehost_proto protoreflect.FileDescriptor

var file_heyp_proto_fakehost_proto_rawDesc = []byte{
	0x0a, 0x19, 0x68, 0x65, 0x79, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x61, 0x6b,
	0x65, 0x68, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x79,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x06, 0x46, 0x61, 0x6b, 0x65,
	0x46, 0x47, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x72, 0x63, 0x5f, 0x64, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x72, 0x63, 0x44, 0x63, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x73, 0x74,
	0x5f, 0x64, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x73, 0x74, 0x44, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a,
	0x6f, 0x62, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x69, 0x6e, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x48,
	0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x6d, 0x61, 0x78, 0x48, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x5f, 0x62, 0x70, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x42, 0x70,
	0x73, 0x12, 0x31, 0x0a, 0x12, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x5f,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x3a, 0x03, 0x32,
	0x30, 0x30, 0x52, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x08, 0x46, 0x61, 0x6b, 0x65, 0x48, 0x6f, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x67, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x66, 0x67, 0x49, 0x64, 0x73,
	0x22, 0x8a, 0x01, 0x0a, 0x13, 0x48, 0x6f, 0x73, 0x74, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x03, 0x66, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x65, 0x79, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x61, 0x6b, 0x65, 0x46, 0x47, 0x52, 0x03, 0x66, 0x67, 0x73, 0x12, 0x2a,
	0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x68, 0x65, 0x79, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x61, 0x6b, 0x65, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0a, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x64, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x02,
	0x33, 0x73, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x75, 0x72, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x6c, 0x75, 0x79,
	0x6f, 0x6c, 0x2f, 0x68, 0x65, 0x79, 0x70, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67,
	0x6f, 0x2f, 0x70, 0x62,
}

var (
	file_heyp_proto_fakehost_proto_rawDescOnce sync.Once
	file_heyp_proto_fakehost_proto_rawDescData = file_heyp_proto_fakehost_proto_rawDesc
)

func file_heyp_proto_fakehost_proto_rawDescGZIP() []byte {
	file_heyp_proto_fakehost_proto_rawDescOnce.Do(func() {
		file_heyp_proto_fakehost_proto_rawDescData = protoimpl.X.CompressGZIP(file_heyp_proto_fakehost_proto_rawDescData)
	})
	return file_heyp_proto_fakehost_proto_rawDescData
}

var file_heyp_proto_fakehost_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_heyp_proto_fakehost_proto_goTypes = []interface{}{
	(*FakeFG)(nil),              // 0: heyp.proto.FakeFG
	(*FakeHost)(nil),            // 1: heyp.proto.FakeHost
	(*HostSimulatorConfig)(nil), // 2: heyp.proto.HostSimulatorConfig
}
var file_heyp_proto_fakehost_proto_depIdxs = []int32{
	0, // 0: heyp.proto.HostSimulatorConfig.fgs:type_name -> heyp.proto.FakeFG
	1, // 1: heyp.proto.HostSimulatorConfig.hosts:type_name -> heyp.proto.FakeHost
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_heyp_proto_fakehost_proto_init() }
func file_heyp_proto_fakehost_proto_init() {
	if File_heyp_proto_fakehost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heyp_proto_fakehost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FakeFG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_heyp_proto_fakehost_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FakeHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_heyp_proto_fakehost_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostSimulatorConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heyp_proto_fakehost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heyp_proto_fakehost_proto_goTypes,
		DependencyIndexes: file_heyp_proto_fakehost_proto_depIdxs,
		MessageInfos:      file_heyp_proto_fakehost_proto_msgTypes,
	}.Build()
	File_heyp_proto_fakehost_proto = out.File
	file_heyp_proto_fakehost_proto_rawDesc = nil
	file_heyp_proto_fakehost_proto_goTypes = nil
	file_heyp_proto_fakehost_proto_depIdxs = nil
}
