package stats

// Code generated by gen.go. DO NOT EDIT.

type HostGlobalTCPStats struct {
	ActiveOpens  int64
	AttemptFails int64
	CurrEstab    int64
	EstabResets  int64
	InCsumErrors int64
	InErrs       int64
	InSegs       int64
	MaxConn      int64
	OutRsts      int64
	OutSegs      int64
	PassiveOpens int64
	RetransSegs  int64
	RtoAlgorithm int64
	RtoMax       int64
	RtoMin       int64
}

func (st *HostGlobalTCPStats) Update(s string, v int64) {
	switch s {
	case "ActiveOpens":
		st.ActiveOpens = v
	case "AttemptFails":
		st.AttemptFails = v
	case "CurrEstab":
		st.CurrEstab = v
	case "EstabResets":
		st.EstabResets = v
	case "InCsumErrors":
		st.InCsumErrors = v
	case "InErrs":
		st.InErrs = v
	case "InSegs":
		st.InSegs = v
	case "MaxConn":
		st.MaxConn = v
	case "OutRsts":
		st.OutRsts = v
	case "OutSegs":
		st.OutSegs = v
	case "PassiveOpens":
		st.PassiveOpens = v
	case "RetransSegs":
		st.RetransSegs = v
	case "RtoAlgorithm":
		st.RtoAlgorithm = v
	case "RtoMax":
		st.RtoMax = v
	case "RtoMin":
		st.RtoMin = v
	}
}
func (st *HostGlobalTCPStats) Sub(o *HostGlobalTCPStats) HostGlobalTCPStats {
	var diff HostGlobalTCPStats
	diff.ActiveOpens = st.ActiveOpens - o.ActiveOpens
	diff.AttemptFails = st.AttemptFails - o.AttemptFails
	diff.CurrEstab = st.CurrEstab - o.CurrEstab
	diff.EstabResets = st.EstabResets - o.EstabResets
	diff.InCsumErrors = st.InCsumErrors - o.InCsumErrors
	diff.InErrs = st.InErrs - o.InErrs
	diff.InSegs = st.InSegs - o.InSegs
	diff.MaxConn = st.MaxConn - o.MaxConn
	diff.OutRsts = st.OutRsts - o.OutRsts
	diff.OutSegs = st.OutSegs - o.OutSegs
	diff.PassiveOpens = st.PassiveOpens - o.PassiveOpens
	diff.RetransSegs = st.RetransSegs - o.RetransSegs
	diff.RtoAlgorithm = st.RtoAlgorithm - o.RtoAlgorithm
	diff.RtoMax = st.RtoMax - o.RtoMax
	diff.RtoMin = st.RtoMin - o.RtoMin
	return diff
}
